"""Report renderer: adds metadata header/footer to Claude's analysis."""

from datetime import datetime, timezone
from tools import ToolResult


def render(apk_name: str, metadata: dict, analysis_md: str, tool_results: list[ToolResult]) -> str:
    risk = _extract_risk(analysis_md)
    tool_status = _tool_status(tool_results)

    header = f"""\
# APK Security Report: {metadata.get('app_name', apk_name)}

| Field | Value |
|-------|-------|
| File | `{apk_name}` |
| Package | `{metadata.get('package', 'unknown')}` |
| Version | {metadata.get('version', 'N/A')} |
| Size | {metadata.get('size_mb', '?')} MB |
| SHA256 | `{metadata.get('sha256', 'N/A')}` |
| Risk Level | **{risk}** |
| MobSF Score | {metadata.get('security_score', 'N/A')} / 100  (CVSS avg: {metadata.get('average_cvss', 'N/A')}) |
| Analyzed | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} |

---
"""

    footer = f"""

---
## Tool Status
{tool_status}

---
*Generated by APK Security Analyzer*
*Model: {metadata.get('model', 'claude-sonnet-4-6')} | Tools: APKLeaks · MobSF · JADX*
"""
    return header + analysis_md + footer


def _extract_risk(md: str) -> str:
    """Best-effort risk level from Claude's report text."""
    for line in md.splitlines():
        for level in ("CRITICAL", "HIGH", "MEDIUM", "LOW"):
            if level in line.upper() and ("risk" in line.lower() or "level" in line.lower()):
                return level
    # Infer from findings sections
    if "🔴" in md:
        return "CRITICAL"
    if "🟠" in md:
        return "HIGH"
    if "🟡" in md:
        return "MEDIUM"
    return "LOW"


def _tool_status(results: list[ToolResult]) -> str:
    rows = []
    for r in results:
        icon = "✅" if r.ok else "❌"
        extra = ""
        if r.name == "jadx" and r.ok:
            extra = f" ({r.data.get('java_files', 0)} Java files)"
        if r.name == "mobsf" and r.ok:
            extra = f" (hash: {r.data.get('hash', '')[:8]}…)"
        if not r.ok and r.error:
            extra = f" — {r.error[:80]}"
        rows.append(f"- {icon} **{r.name}**{extra}")
    return "\n".join(rows)
